dist: trusty

language: node_js

node_js:
  - lts/*

install:
  - curl -O https://download.clojure.org/install/linux-install-1.10.0.411.sh
  - chmod +x linux-install-1.10.0.411.sh
  - sudo ./linux-install-1.10.0.411.sh

script:
  - if [[ $CANARY_CLOJURESCRIPT_REPO && ${CANARY_CLOJURESCRIPT_REPO-x} ]]; then DEPS="{:paths [\"src/test\" \"src/main/clojure\"] :deps {org.clojure/clojurescript {:git/url \"${CANARY_CLOJURESCRIPT_REPO}\" :sha \"${CANARY_CLOJURESCRIPT_REV}\"}}}"; fi
  - clojure -Sdeps "${DEPS:-{:paths [\"src/test\" \"src/main/clojure\"] :deps {org.clojure/clojurescript {:mvn/version \"1.10.439\"}}}}" -m cljs.main -re node src/test/cljs/core/match/tests.cljs | tee test-out.txt
  - grep '0 failures, 0 errors.' test-out.txt
